from pathlib import Path
import re, json, sys
root = Path(__file__).resolve().parents[1]
js = (root/'game-v79-defense.js').read_text()
css = (root/'launch-v79-defense-alive.css').read_text()
index = (root/'index.html').read_text()
sw = (root/'sw.js').read_text()
core = (root/'defense-core-v79.js').read_text()
checks = {}
def check(name, value, detail=''):
    checks[name] = {'passed': bool(value), 'detail': detail}

check('production QA uses a single gated namespace', 'if(IS_QA_BUILD)window.RizoRuntimeQA=createRizoRuntimeQA()' in js)
check('legacy QA namespaces are not assigned', 'window.RizoVisualQA =' not in js and 'window.RizoVisualQA=' not in js and 'window.RizoBeatQA=' not in js)
check('no direct QA helper globals', not re.search(r'window\.defense\w+ForQA\s*=', js))
check('currentWave and clearedWave state exist', 'currentWave:0,clearedWave:0' in js)
check('whole-save envelope is signed', 'buildStateEnvelope' in js and 'createStateSignature' in js and 'verifyStateSignature' in js)
check('verified save backup recovery exists', 'SAVE_BACKUP_KEY' in js and 'primary-signature-recovered' in js)
check('invalid checkpoints fail closed', 'restoredClearedWave' in js and 'cash:trusted?' in js and 'upgrade=trusted?' in js)
check('checkpoint canonicalization rejects unknown pet ids', 'if(!owner)return null' in js and 'defenseCheckpointRosterRegistry' in js)
check('completion verifies full resolution', 'd.currentWave<=d.clearedWave' in js and '!isWaveFullyResolved(d))return false' in js)
check('child queue blocks completion', 'd.childSpawnQueue.length===0' in js)
check('rewards calculate from clearedWave', 'calculateRunEmbers({clearedWave,' in js)
check('zero-clear runs cannot advance mastery', 'if(clearedWave>0)for(const row of persistentLeaders)' in js)
check('run outcomes are explicit', 'finishDefenseRunWithMoment("banked")' in js and 'finishDefenseRunWithMoment("gate")' in js and 'ended:snapshot.ended==="gate"?"gate":"banked"' in js)
check('history migration preserves reached wave', 'reachedWave = Math.max(clearedWave' in js and 'clearedWave,' in js)
check('golden bonus only has one implementation', len(re.findall(r'^\s{2}function defenseGoldenBonus\(', js, re.M)) == 1)
check('gameplay density uses centralized invariant core', 'DefenseCore.densityCap' in js and 'speedRoom = speed === 2 ? 2 : 0' not in js)
check('explicit upgrade costs are active', 'DefenseCore.upgradeCost' in js and '110 + 80 * upgrade' not in js)
check('simulation and control clocks are separated', 'realClock:0' in js and 'd.realClock=(d.realClock||0)+safeRealDt' in js and 'd.clock+=dt' in js)
check('v76 uses fixed 30hz simulation with bounded catch-up', 'stepHz: 30' in core and 'maxCatchUpSteps: 4' in core and 'advanceDefenseFixedFrame' in js and 'simAccumulator' in js)
check('presentation interpolates simulation snapshots', 'renderDefensePresentation' in js and 'enemy.prevX+(enemy.x-enemy.prevX)*blend' in js)
check('adaptive governor tracks p95 and degrades presentation first', 'frameP95' in js and 'governorTier' in js and 'presentationFps' in core and 'performanceLow=(d.governorTier||0)>=2' in js)
check('logical projectile simulation is decoupled from visual emission', 'projectileEmissionHz' in core and 'coalescedVisualShots' in js and 'defenseVisibleProjectileCount' in js)
check('speed and quality do not secretly thin gameplay density', 'void low; void speed;' in core and 'DefenseCore.densityCap({low:false' in js)
check('manual wave boundaries remain default with optional auto waves', 'defenseAutoStart: false' in js and 'data-defense-auto-start' in js and 'autoStartAtReal' in js)
check('target refresh uses simulation time and cached references', 'realTime=time,budget=DEFENSE_BUDGETS.normal' in js and 'tower.targetRef' in js and 'targetSnapshotAtReal' in js)
check('split children use deterministic game-time release', 'releaseAt:d.clock+Math.max(.04,delay)' in js and 'child.releaseAt>d.clock' in js and 'childSpawnsReleased' in js)
check('child buffer is not sorted every frame', '.childSpawnQueue.sort(' not in js)
check('density reserves imminent child spawns', 'DefenseCore.childReservationCount' in js)
check('boss entries have no density bypass', 'isBoss&&!d.enemies.some' not in js and 'active<Math.min(10,cap)' not in js)
check('2x visual budgets lower effects', 'DefenseCore.visualBudget' in js and '--defense-weather-density' in js and '--defense-weather-density' in css)
check('income flush cadence uses wall time', 'nextIncomeFlushAtReal' in js and 'lastIncomeBatch' in js)
check('v87 checkpoint migrates v80 and older data', 'defense-checkpoint-v68' in js and 'defense-checkpoint-v67' in js and '[1,2,3,4,5,6,7,DEFENSE_CHECKPOINT_VERSION]' in js)
check('new service worker cache matches build', 'rizo-game-v87-first-ten' in sw and 'defense-core-v79.js' in sw and 'game-v79-defense.js' in sw and 'game-v63-art-direction.js' not in sw)
check('index build metadata matches v87', index.count('v87-first-ten') >= 2 and 'v75-arcade-revival' not in index)
check('index loads active defense assets', 'defense-core-v79.js' in index and 'defense-canvas-v79.js' in index and 'game-v79-defense.js' in index and 'launch-v79-defense-alive.css' in index)
check('defense css has no important declarations', not re.search(r'(?:mini-game-overlay\.defense-active|defense-|rizo-defense|balloon-|boss-)[^{]*\{[^}]*!important', css, re.S))
check('no uncontrolled defense z-index literals', not re.search(r'(?:defense-|defense-active)[^{]*\{[^}]*(?:z-index\s*:\s*(?:999|[1-9]\d{3,}))', css, re.S))
check('media query count reduced', css.count('@media') <= 30, f"count={css.count('@media')}")
check('important count materially reduced', css.count('!important') < 400, f"count={css.count('!important')}")
check('stylesheet smaller than original', len(css) < 300_000, f"bytes={len(css)}")
check('obsolete per-world starting cash removed', not re.search(r'const DEFENSE_MAPS[\s\S]{0,12000}?cash:\d+', js))
check('phase 5 economy is centralized in core', 'const ECONOMY = Object.freeze' in (root/'defense-core-v79.js').read_text() and 'baseStartingCash: 220' in (root/'defense-core-v79.js').read_text())
check('late economy uses normalized bounty and late deployment growth', 'packNormalization' in (root/'defense-core-v79.js').read_text() and 'deployLateGrowth: 1.62' in (root/'defense-core-v79.js').read_text() and 'UPGRADE_COSTS = Object.freeze([110, 180, 320, 640])' in (root/'defense-core-v79.js').read_text())
check('all maps share one starting-cash contract', 'cash:BASE_DEFENSE_STARTING_CASH' in js and not re.search(r'const DEFENSE_MAPS[\s\S]{0,16000}?cash:\d+', js))
check('map reward multipliers no longer inflate defense economy', 'map.reward' not in js and 'calculateWaveBonus({clearedWave:' in js and 'calculateRunEmbers({clearedWave,' in js)
catalog_match = re.search(r'const DEFENSE_ENEMIES = \{([\s\S]+?)const DEFENSE_MILESTONES', js)
catalog_rewards = [int(value) for value in re.findall(r'reward:(\d+)', catalog_match.group(1) if catalog_match else '')]
check('canonical enemy and boss/heavy kill rewards remain defined', len(catalog_rewards) == 15 and min(catalog_rewards, default=0) > 0, f"count={len(catalog_rewards)} rewards={catalog_rewards}")
check('deployment cost is canonical and not duplicated in runtime', 'DefenseCore.deploymentCost' in js and '145*Math.pow(1.36' not in js)
check('planning refund and undo use centralized wall-time rules', 'DefenseCore.ECONOMY.planningRefundRate' in js and 'DefenseCore.ECONOMY.placementUndoSeconds' in js and 'placedAtReal:defenseRealNow(d)' in js)
check('combat economy permissions use phase model with live upgrades', 'function defenseUpgradeAllowed' in js and 'function defensePlacementAllowed' in js and 'function defenseSellAllowed' in js and 'SAFE WINDOW REQUIRED' not in js)
check('world opening perks are explicit and one-shot', 'DEFENSE_WORLD_OPENING_PERKS' in js and 'worldOpeningDiscount' in js and 'openingPerkApplied' in js and 'worldPerkUsed' in js)
check('Golden global and active income use capped core functions', 'DefenseCore.goldenBonus' in js and 'DefenseCore.goldenActivePayout' in js and 'gain=45+d.currentWave' not in js)
check('v5 checkpoint signature covers opening economy state', 'signatureVersion >= 5' in (root/'defense-core-v79.js').read_text() and 'signedTower.openingPerkApplied' in (root/'defense-core-v79.js').read_text() and 'modern.worldPerkUsed' in (root/'defense-core-v79.js').read_text())
boot=index
headers=(root/'_headers').read_text()
config=(root/'rizo-config.js').read_text()
core=(root/'defense-core-v79.js').read_text()
check('bosses reserve a dedicated final packet entrance', 'Bosses own the last beat' in core and 'packets.push({ enemies: [bossEntry], spawnGap: 1.10, breakAfter: 0 })' in core)
check('obsolete runtime spawn pacing workarounds are removed', 'function defenseSpawnGap(' not in js and 'function defenseSpawnClearance(' not in js)
check('phase transitions are explicit and validated', 'PHASE_TRANSITIONS' in core and 'canTransitionPhase' in core and 'phase-transition-rejected' in js)
check('persistent phase HUD shows active and cleared waves separately', 'id="defenseWave"' in js and 'id="defenseClearedWave"' in js and 'id="defensePhaseIndicator"' in js)
check('context overlays use one manager with inert background', 'syncDefenseOverlayState' in js and 'defenseContextSurface' in js and '.inert=' in js and 'data-defense-dismiss-context' in js)
check('context keyboard handling traps focus and handles Escape', 'defenseHandleContextKeydown' in js and 'event.key==="Escape"' in js and 'event.key!=="Tab"' in js)
check('portrait shell has an explicit minmax column contract', 'grid-template-columns: minmax(0, 1fr); grid-template-rows:' in css)
check('short portrait preserves hearts, gold, wave and phase', '.defense-command-world { display:none; }' in css and 'grid-template-columns:repeat(3,minmax(44px,1fr))' in css and '#defenseWaveLabel { display:block; }' in css)
check('large cash is compacted only at HUD presentation', 'function defenseHudCounter' in js and 'cash.textContent=defenseHudCounter(exact)' in js)
check('boot recovery is inline and survives external runtime failure', 'id="rizo-boot-inline"' in boot and 'Mixed build detected' in boot and 'REPAIR APP CACHE' in boot and 'window.RizoBoot' in boot and 'boot-v72-final-product.js' not in index)
check('automatic install gate is disabled at launch', 'enabled: false' in config)
check('service worker core runtime is network first', 'NETWORK_FIRST_PATHS' in sw and 'networkFirst(request)' in sw and 'fetch(request, { cache: "no-store" })' in sw)
check('service worker optional shell cannot fail update atomically', 'cache.addAll(REQUIRED_SHELL)' in sw and 'Promise.allSettled' in sw)
check('service worker converges after complete shell cache', 'await self.skipWaiting()' in sw and 'self.clients.claim()' in sw)
check('deployment MIME and cache headers are explicit', 'X-Content-Type-Options: nosniff' in headers and '/*.js' in headers and 'Content-Type: application/javascript' in headers and '/*.css' in headers and 'Content-Type: text/css' in headers)
active_text = '\n'.join([index, css, js, sw])
asset_refs = sorted(set(re.findall(r'\./assets/[A-Za-z0-9_./-]+\.(?:png|webp|svg|jpg|jpeg|gif|mp3|wav|ogg)', active_text, re.I)))
missing_assets = [ref for ref in asset_refs if not (root/ref[2:]).exists()]
check('all active local assets exist', not missing_assets, f"refs={len(asset_refs)} missing={missing_assets[:8]}")

# Phase 7 battlefield art cohesion contracts.
check('phase 7 structural world feature layer is canonical', 'function defenseWorldFeatureMarkup(map)' in js and '<div class="defense-world-features">${defenseWorldFeatureMarkup(map)}</div>' in js)
check('all six worlds define authored terrain feature identities', all(token in js for token in ['root','vine','vent','crack','orbit','crater','puddle','wind','bank','lane','reveal']))
landmark_block = re.search(r'\.defense-landmark\s*\{([^}]*)\}', css, re.S)
check('generic landmark rule no longer flattens authored silhouettes', bool(landmark_block) and 'width:' not in landmark_block.group(1) and 'height:' not in landmark_block.group(1) and 'background:' not in landmark_block.group(1), landmark_block.group(1).strip() if landmark_block else 'missing')
check('road fill weight is reduced from legacy width', '.defense-road-fill { stroke:var(--road-fill); stroke-width:58;' in css and 'stroke-width:67' not in css)
check('adaptive gameplay contrast variables exist for all worlds', css.count('--play-outline:') >= 7 and css.count('--play-halo:') >= 7, f"outline={css.count('--play-outline:')} halo={css.count('--play-halo:')}")
check('tower and enemy geometry share bounded world scale', 'clamp(d.renderWidth/390,.86,1.16)' in js and 'width:calc(62px * var(--def-unit-scale))' in css and 'width:calc(36px * var(--def-unit-scale))' in css)
check('selected tower uses dedicated ground range surface', '.defense-tower.selected .defense-range { opacity:1; }' in css and '.defense-range {' in css)
check('placement pockets carry world identity classes', 'build-pocket-${escapeHTML(map.id)}' in js and all(f'.build-pocket-{m}' in css for m in ['ember','moon','storm','blizzard','eclipse']))
check('route markers are quiet until explicit trace state', '.defense-route-marker {' in css and 'opacity:0;' in css and '.defense-world.route-tracing .defense-route-marker { opacity:.55; }' in css and 'route-tracing' in js)
check('development-style world labels are visually removed', '.defense-landmark span, .defense-route-marker span, .defense-entrance span, .defense-gate b { display:none; }' in css)
check('tower grounding uses foot shadow and pedestal contracts', '.defense-tower::before {' in css and '.defense-tower::after {' in css and 'translate:-50% -88%' in css)
check('phase 7 adds no defense important override debt', not re.search(r'(?:defense-|balloon-)[^{]*\{[^}]*!important', css, re.S))

out = root/'reports'/'static-defense-audit.json'
out.write_text(json.dumps(checks, indent=2))
for name, row in checks.items(): print(('PASS' if row['passed'] else 'FAIL'), name, row['detail'])
failed = [name for name,row in checks.items() if not row['passed']]
print(f"\n{len(checks)-len(failed)}/{len(checks)} static checks passed")
sys.exit(1 if failed else 0)
